### ISSUE TITLE
Channel id must be a positive integer

### ISSUE THREAD

**Issue by Qoyyuum** [asamonik/nvim-screenshot#1]
After installing the plugin, I tried to run the `:Screenshot` but I got this error:

```
Error detected while processing function remote#define#request:
line    2:
E475: Invalid argument: Channel id must be a positive integer
```

**Comment by asamonik** [comment]
Hello, I tried to reproduce it but I was not able to. Can you share your nvim version? Thanks

**Comment by Qoyyuum** [comment]
Thanks @asamonik . I'm using Windows 10 if that matters.

```
> nvim -v
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az276-503

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

```

**Comment by asamonik** [comment]
Should now work. The plugin now tries to find a main.exe if no main is found since go build creates a .exe on windows.

**Comment by Qoyyuum** [comment]
Hey @asamonik I tried it after `:PlugUpdate` and found that I don't have go installed. 

![image](https://user-images.githubusercontent.com/971309/187928519-8af1b65e-1e51-4e17-972c-0336d43a16de.png)

After installing golang, and verifying that I can run go,

```
> go version
go version go1.19 windows/amd64
```

I tried to run `:Screenshot` again but it couldn't find the go binary still.

The go binary installed on Windows is defaulted to `%USERPROFILE%\go` directory assigned to `GOPATH` environment variable. So I don't know what its trying to do.

Error message for reference:

```
cannot find go binary
Error detected while processing function remote#define#CommandBootstrap[1]..remote#host#Require[10]..<SNR>20_Start_nvim_screenshot:
line    8:
E168: :finish used outside of a sourced file
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
E475: Invalid argument: Channel id must be a positive integer
Press ENTER or type command to continue
```

**Comment by Qoyyuum** [comment]
I found the difference. I default to Powershell instead of cmd, so the environment variable to access the GOPATH is slightly different.

On Powershell: `$env:USERPROFILE\go`
On CMD: `%USERPROFILE%\go`
